version: '3.6'

services:
  # Build commands for main flask app
  flask:
    build:
      context: .
      dockerfile: ./compose/local/flask/Dockerfile
    image: dapp_store_backend_test_flask
    depends_on:
      - postgres
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - ./.envs/.test/.flask
      - ./.envs/.test/.postgres
    command: /test

  # Build commands for postgres db
  postgres:
    build:
      context: .
      dockerfile: ./compose/local/postgres/Dockerfile
    image: dapp_store_backend_test_postgres
    ports:
      - "5432:5432"
    env_file:
      - ./.envs/.test/.postgres
    networks:
      default:
        aliases:
          - dapp_postgres
