"""empty message

Revision ID: 5fb34d197a8f
Revises: bb491f18af06
Create Date: 2018-09-26 20:02:57.795410

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5fb34d197a8f'
down_revision = 'bb491f18af06'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('review', sa.Column('data', postgresql.JSONB(), nullable=False))
    op.add_column('review', sa.Column('verified', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('review', 'verified')
    op.drop_column('review', 'data')
    # ### end Alembic commands ###
