"""empty message

Revision ID: 6bf51f2089ca
Revises: 5fb34d197a8f
Create Date: 2018-10-01 06:16:56.420559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bf51f2089ca'
down_revision = '5fb34d197a8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('featured',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page', sa.SmallInteger(), nullable=False),
    sa.Column('position', sa.SmallInteger(), nullable=False),
    sa.Column('dapp_id', sa.Integer(), nullable=False),
    sa.Column('banner_path', sa.String(length=100), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dapp_id'], ['dapp.id'], ),
    sa.ForeignKeyConstraint(['page'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('banner_path'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('featured')
    # ### end Alembic commands ###
