#!/bin/sh

set -o errexit
set -o pipefail
set -o nounset

INIT_DATA=false

# Initialize database if migrations folder does not exist
if [ ! -d "migrations" ]; then
    python manage.py db init
    INIT_DATA=true
fi

# Initialize and migrate database
#flask db migrate
flask db upgrade

#flask translate compile
exec gunicorn -b :8000 --log-level debug --access-logfile - --error-logfile - wsgi:app
